config/routes.rb
Rails.application.routes.draw do
 
root 'home#index'
#get '/' => 'home#index'



  resources :distilleries do
    # nested resource for bourbon
        resources :bourbons, only: [:show, :index, :new, :edit]
         end
 resources :bourbons

 resources :stockists
 
 resources :bourbon_stockists

 get '/rare' => 'bourbons#rare'
 get '/oldest' =>'bourbons#oldest'

#get '/bourbon_stockists/new' => 'bourbon_stockists#new'
#post '/bourbon_stockists' => 'bourbon_stockists#create'
#get '/bourbon_stockists' => 'bourbon_stockists#index'


  get 'bourbons/:id/bourbon_data', to: 'bourbons#bourbon_data'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
post '/logout' => 'sessions#destroy'  #do you need this route?

get '/auth/facebook/callback' => 'sessions#create'

get '/welcome' => 'welcome#home'

#get '/signup'  => 'users#new'
#post '/signup' => 'users#create'



resources :users, only: [:new, :create]
end

app/models/bourbon_stockist.rb
class BourbonStockist < ApplicationRecord
  belongs_to :bourbon
  belongs_to :stockist


  validates :notes, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }


  def stockist_name
      self.stockist ? self.stockist.name : nil
    end



end

app/controllers/bourbon_stockists_controller.rb
class BourbonStockistsController < ApplicationController
  before_action :require_logged_in
  before_action :find_bourbon_stockist, except: [:index, :new, :create]

  helper :all

def new
  @bourbon_stockist = BourbonStockist.new

end


def create
  @bourbon_stockist = BourbonStockist.new(bourbon_stockist_params)
  if @bourbon_stockist.save
    redirect_to @bourbon_stockist.bourbon
   else
  render :new
   end
end

def index
  @bourbon_stockists = BourbonStockist.all
end

def edit
end

def show
end

def update
  @bourbon_stockist.update(bourbon_stockist_params)
  if @bourbon_stockist.save
    redirect_to @bourbon_stockist
  else
    render :edit
   end
end

  def destroy
    @bourbon_stockist.destroy
    flash[:notice] = "Note deleted"
    redirect_to bourbons_path
  end





private

def bourbon_stockist_params
   params.require(:bourbon_stockist).permit(:notes, :bourbon_id, :stockist_id)
end

def find_bourbon_stockist
  @bourbon_stockist = BourbonStockist.find(params[:id])
end

end

app/helpers/bourbon_stockists_helper.rb
module BourbonStockistsHelper

  #def last_updated(bourbon_stockist)
    #bourbon_stockist[:created_at].strftime('%F %T')
  #end - not working.

end

app/views/bourbon_stockists/_form.html.erb
<% if @bourbon_stockist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@bourbon_stockist.errors.count, "error") %>
      prohibited this note from being saved:
    </h2>

    <ul>
    <% @bourbon_stockist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @bourbon_stockist do |f| %>

   Select Bourbon:
  <%= f.collection_select :bourbon_id, Bourbon.all, :id, :name %> </br>
  Select Stockist:
  <%= f.collection_select :stockist_id, Stockist.all, :id, :name %></br>
  <%= f.label :notes%>
  <%= f.text_field :notes %><br>

  <%= f.submit 'submit' %>
<% end %>

app/views/bourbon_stockists/edit.html.erb
<h1>Edit Note</h1>
<%= render partial: "form" %>

</br>
<%= link_to "Delete Note", @bourbon_stockist, method: :delete, data: { confirm: "Really?" } %>
</br>
<br>
<%= link_to "Notes Index", bourbon_stockists_path %> </br>
</br>
<%= link_to "Distillery Index List", distilleries_path %> </br>
<%= link_to "Stockist Index List", stockists_path %></br>
<%= link_to "Bourbon Index List", bourbons_path %>

app/views/bourbon_stockists/index.html.erb
<h1> Stockist Notes Index </h1>



<% @bourbon_stockists.each do |bourbon_stockist| %>
<%= bourbon_stockist.notes %></br>
<%= bourbon_stockist.bourbon.name%></br>
<%= bourbon_stockist.stockist_name%></br>

<%= link_to "Edit Note", edit_bourbon_stockist_path(bourbon_stockist) %> </br>
</br>
<% end %>

<br>
<%= link_to "Add New Note", new_bourbon_stockist_path %> </br>
</br>
<%= link_to "Distillery Index List", distilleries_path %> </br>
<%= link_to "Stockist Index List", stockists_path %></br>
<%= link_to "Bourbon Index List", bourbons_path %>

app/views/bourbon_stockists/new.html.erb
<h1>Create a New Note </h1>
<%= render partial: "form" %>

app/views/bourbon_stockists/show.html.erb
Notes for
<h1><%= @bourbon_stockist.bourbon.name %></h1>

from:

<h2><%= @bourbon_stockist.stockist_name %> </h2></br>
  <h2><%= @bourbon_stockist.notes %> </h2></br>

</br>
<%= link_to @bourbon_stockist.bourbon.name, bourbon_path(@bourbon_stockist.bourbon) %> </br>
</br>
<%= link_to 'Edit Note', edit_bourbon_stockist_path %> </br>
</br>
<%= link_to @bourbon_stockist.stockist_name, stockist_path(@bourbon_stockist.stockist) %>