config/routes.rb
Rails.application.routes.draw do
 
root 'home#index'
#get '/' => 'home#index'



  resources :distilleries do
    # nested resource for bourbon
        resources :bourbons, only: [:show, :index, :new, :edit]
         end
 resources :bourbons

 resources :stockists
 
 resources :bourbon_stockists

 get '/rare' => 'bourbons#rare'
 get '/oldest' =>'bourbons#oldest'

#get '/bourbon_stockists/new' => 'bourbon_stockists#new'
#post '/bourbon_stockists' => 'bourbon_stockists#create'
#get '/bourbon_stockists' => 'bourbon_stockists#index'


  get 'bourbons/:id/bourbon_data', to: 'bourbons#bourbon_data'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
post '/logout' => 'sessions#destroy'  #do you need this route?

get '/auth/facebook/callback' => 'sessions#create'

get '/welcome' => 'welcome#home'

#get '/signup'  => 'users#new'
#post '/signup' => 'users#create'



resources :users, only: [:new, :create]
end

app/models/stockist.rb
class Stockist < ApplicationRecord

  has_many :bourbon_stockists
  has_many :bourbons, through: :bourbon_stockists


    after_save { |stockist| stockist.destroy if stockist.name.blank? }


  #before_create :remove_stockists_without_name

  #before_save :destroy_if_blank


  def bourbon_count
    self.bourbons.size
  end

  #private
  #def destroy_if_blank
    #logger.info "destroy_if_blank called"
  #end

end

app/controllers/stockists_controller.rb
class StockistsController < ApplicationController
  # before_action :require_logged_in
  before_action :find_stockist, except: [:index, :new, :create]

	# skip_before_action :verify_authenticity_token
	

	def index
    @stockists = Stockist.all
		@stockist = Stockist.new
		 
		respond_to do |f|
			f.html {render :index}
			f.json {render :json => @stockists}
		end
  end

	def show
		render json: @stockist
  end

  def new
    @stockist = Stockist.new
  end

	def create
    @stockist = Stockist.new(stockist_params)		
    if @stockist.save
      respond_to do |f|
				f.html {redirect_to stockists_path(@stockist)}
				f.json {render :json => @stockist}
      end
		else
      # render :index
		end
  end
	
  def edit
  end
	
  def update
    @stockist.update(stockist_params)
    if @stockist.save
      redirect_to @stockist
    else
      render :edit
		end
  end
	
  def destroy
    @stockist.destroy
    flash[:notice] = "Stockist deleted"
    redirect_to stockists_path
  end
	
  private
		def stockist_params
			params.require(:stockist).permit(:name, :address, :email, :phone, :bourbon_ids => [])
		end
		
		def find_stockist
			@stockist = Stockist.find(params[:id])
		end

end

app/views/stockists/_form.html.erb
<% if @stockist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@stockist.errors.count, "error") %>
      prohibited this stockist from being saved:
    </h2>

    <ul>
    <% @stockist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @stockist do |f| %>
</br>
<%= f.label :name%>
<%= f.text_field :name %><br>
<%= f.label :address%>
<%= f.text_field :address %><br>
<%= f.label :email%>
<%= f.text_field :email %><br>
<%= f.label :phone%>
<%= f.text_field :phone %></br>

</br>

   Select bourbons on stock:
  <%= f.collection_check_boxes :bourbon_ids, Bourbon.all, :id, :name %> </br>

</br>
</br>
  <%= f.submit %>
<% end %>
</br>
<%= link_to 'All Bourbons', bourbons_path %> </br>
</br>
<%= link_to 'All Stockists', stockists_path %> </br>
</br>
<%= link_to 'All Distilleries', distilleries_path %>

app/views/stockists/edit.html.erb
<h1>Editing <%= @stockist.name %></h1>
<%= render partial: "form" %>
</br>
<%= link_to "Delete Stockist", @stockist, method: :delete, data: { confirm: "Really?" } %>

app/views/stockists/index.html.erb
<body>
<h1> Stockists Index </h1>
<br>


<div id="stockist-form">
	<%= form_for(@stockist) do |f| %>
		<%= f.text_area :name %>
		<%= f.text_area :address %>
		<%= f.submit :submit %>
	<% end %>

<ul class="new-stockist"></ul>
</div>

<div id='stockist-detail'></div>

<script id="stockist-template" type="text/x-handlebars-template">
  <div class="name">
    <h1>{{name}}</h1>
    <div class="address">
      {{address}}
    </div>
  </div>
</script>

<div id='stockists-index'>
	<% @stockists.each do |stockist| %>
	<%= link_to stockist.name, stockist_path(stockist), id: stockist.id %><br>
	<% end %>
</div>



</body>

app/views/stockists/new.html.erb
<h1>Create a New Stockist </h1>
<%= render partial: "form" %>

app/views/stockists/show.html.erb
<h1><%= @stockist.name %></h1> <br>
<%= @stockist.address %> <br>
<%= @stockist.email %> <br>
<%= @stockist.phone %> <br>
</br>
(<%= @stockist.bourbon_count %> <%= "bourbon".pluralize(@stockist.bourbon_count) %>) in stock


<h2>List of bourbons at <%= @stockist.name %></h2>
<% @stockist.bourbons.uniq.each do |bourbon| %> </br>

<li><%= link_to bourbon.name, bourbon_path(bourbon) %></li> </br>
<% end %>
</br>
<%= link_to 'add stockist note ', new_bourbon_stockist_path %></br>

</br>
<%= link_to 'Edit Stockist', edit_stockist_path %> </br>
<%= link_to 'All Stockists', stockists_path %></br>