config/routes.rb
Rails.application.routes.draw do
 
root 'home#index'
#get '/' => 'home#index'



  resources :distilleries do
    # nested resource for bourbon
        resources :bourbons, only: [:show, :index, :new, :edit]
         end
 resources :bourbons

 resources :stockists
 
 resources :bourbon_stockists

 get '/rare' => 'bourbons#rare'
 get '/oldest' =>'bourbons#oldest'

#get '/bourbon_stockists/new' => 'bourbon_stockists#new'
#post '/bourbon_stockists' => 'bourbon_stockists#create'
#get '/bourbon_stockists' => 'bourbon_stockists#index'


  get 'bourbons/:id/bourbon_data', to: 'bourbons#bourbon_data'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
post '/logout' => 'sessions#destroy'  #do you need this route?

get '/auth/facebook/callback' => 'sessions#create'

get '/welcome' => 'welcome#home'

#get '/signup'  => 'users#new'
#post '/signup' => 'users#create'



resources :users, only: [:new, :create]
end

app/models/bourbon.rb
class Bourbon < ApplicationRecord

  belongs_to :distillery
  has_many :bourbon_stockists
  has_many :stockists, through: :bourbon_stockists


  validates :name, presence: true
  validates :age, numericality: true

  scope :rare, -> { where("age = 25") }


  accepts_nested_attributes_for :stockists



def self.oldest
  self.where(age: self.select('MAX(age)'))
end 

def distillery_name
    #self.try(:distillery).try(:distillery)
    #self.distillery.name
    self.distillery ? self.distillery.name : nil
  end

  def distillery_name=(name)
    distillery = Distillery.find_or_create_by(name: name)
    self.distillery = distillery
  end

  def stockists_attributes=(stockist_attributes)
    stockist_attributes.values.each do |stockist_attribute|
      stockist = Stockist.find_or_create_by(stockist_attribute)
      self.stockists << stockist
    end
  end


end

app/controllers/bourbons_controller.rb
class BourbonsController < ApplicationController
before_action :require_logged_in
before_action :find_bourbon, except: [:index, :oldest, :new, :create, :edit]
helper :all


def oldest
  @bourbons = Bourbon.oldest
end



  def index
    if params[:distillery_id]
      @distillery = Distillery.find_by(id: params[:distillery_id])
         if @distillery.nil?
           redirect_to distilleries_path, alert: "Distillery not found"
         else
           @bourbons = @distillery.bourbons #nested resource route
           #render 'bourbons/index', :layout => false
           render :json => @bourbons
         end
    else
    @bourbons = Bourbon.all
  end
end


  def show
    if params[:distillery_id]
      @distillery = Distillery.find_by(id: params[:distillery_id])
      @bourbon = @distillery.bourbons.find_by(id: params[:id])
        if @bourbon.nil?
        redirect_to distillery_bourbons_path(@distillery), alert: 'Bourbon not found'
      end
    else

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @bourbon}
  end
end
end

#BEFORE using a serializer:
      #render json: @post.to_json(only: [:title, :description, :id],
                                #include: [author: { only: [:name]}])
       # AFTER USING OUR SERIALIZER
      #render json: @post, status: 200

def bourbon_data

    render json: @bourbon
  end

  def new
    if params[:distillery_id] && !Distillery.exists?(params[:distillery_id])
    redirect_to distilleries_path, alert: 'Distillery not found.'
      else
    @bourbon = Bourbon.new(distillery_id: params[:distillery_id]) #will ignore if no params
    @bourbon.bourbon_stockists.build
    @bourbon.stockists.build(name: 'name here')

  end
end

  def create
    @bourbon = Bourbon.new(bourbon_params)
    if @bourbon.valid?
      @bourbon.save
      redirect_to bourbon_path(@bourbon)
    else
     render :new
   end
  end


  def edit
    if params[:distillery_id]
    @distillery = Distillery.find_by(params[:distillery_id])
    if distillery.nil?
      redirect_to distilleries_path, alert: 'Distillery not found.'
    else
      @bourbon = distillery.bourbons.find_by(id: params[:id])
      redirect_to distillery_bourbons_path(distillery), alert: 'Bourbon not found.' if
      @bourbon.nil?
      end
    else
    @bourbon = Bourbon.find(params[:id])
    end
  end

  def update
    @bourbon.update(bourbon_params)
    if @bourbon.save
      redirect_to @bourbon
    else
      render :edit
     end
  end

  def destroy
    @bourbon.destroy
    flash[:notice] = "Bourbon deleted"
    redirect_to bourbons_path
  end



  private

  def bourbon_params
    params.require(:bourbon).permit(:name, :age, :grain, :description,
      :distillery_name, :distillery_id,
      :stockists, stockist_ids:[], stockists_attributes: [:name, :address, :email, :phone])
  end

  def find_bourbon
      @bourbon = Bourbon.find(params[:id])
    end

  end

app/helpers/bourbons_helper.rb
module BourbonsHelper

  def rare
    Bourbon.rare
  end

end

app/views/bourbons/_form.html.erb
<% if @bourbon.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@bourbon.errors.count, "error") %>
      prohibited this bourbon from being saved:
    </h2>

    <ul>
    <% @bourbon.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @bourbon do |f| %>

 DISTILLERY:
  <%= f.text_field :distillery_name, list: "distilleries_autocomplete" %>
  <datalist id="distilleries_autocomplete">
    <% Distillery.all.each do |distillery| %>
      <option value="<%= distillery.name %>">
    <% end %>
  </datalist>

</br>
</br>
BOURBON DETAILS:</br>
<%= f.label :name%>
<%= f.text_field :name %><br>
<%= f.label :grain%>
<%= f.text_field :grain %><br>
<%= f.label :age%>
<%= f.text_field :age %><br>
<%= f.label :description%>
<%= f.text_field :description %></br>

</br>

 </br>
 Select stockists: </br>
  <%= f.collection_check_boxes :stockist_ids, Stockist.all, :id, :name %> </br>
</br>
or create new stockist:
<%= f.fields_for :stockists, @bourbon.stockists.build do |stockists_fields| %>
    <%= stockists_fields.label :name %>
    <%= stockists_fields.text_field :name %>
    <%= stockists_fields.label :address %>
    <%= stockists_fields.text_field :address %>
    <%= stockists_fields.label :email %>
    <%= stockists_fields.text_field :email %>
    <%= stockists_fields.label :phone %>
    <%= stockists_fields.text_field :phone %>
<% end %>
</br>
<%= f.submit %>
<% end %>

app/views/bourbons/edit.html.erb
<h1>Editing <%= @bourbon.name %></h1>
<%= render partial: "form" %></br>
<%= link_to "Delete Bourbon", @bourbon, method: :delete, data: { confirm: "Really?" } %>

app/views/bourbons/index.html.erb
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

   <script src="javascripts/bourbons.js" type="text/javascript>"></script>

  </head>

  <h1> Bourbon Index </h1>

<table>
  <tr>
    <th>Distillery</th>
    <th>Bourbon</th>
    <th>Description</th>
  </tr>

<% @bourbons.each do |bourbon| %>
<tr>
<td><%= display_distillery(bourbon) %> </td>
<td><%=link_to bourbon.name, bourbon_path(bourbon) %></td>
<td><div id="body-<%= bourbon.id %>"><%= truncate bourbon.description %></div></td>
<td><button class="js-more" data-id="<%= bourbon.id %>">More...</button></td>
</tr>
<% end %>
</table>


<br>
</br>
<%= link_to "Add New Bourbon", new_bourbon_path %> </br>
</br>
<%= link_to "Rare Bourbons", rare_path %> </br>
</br>
<%= link_to "Distillery Index List", distilleries_path %> </br>
<%= link_to "Stockist Index List", stockists_path %>

app/views/bourbons/new.html.erb
<h1>Create a New Bourbon </h1>
<%= render partial: "form" %>

app/views/bourbons/oldest.html.erb
<% @bourbons.each do |bourbon| %>
<%= bourbon.name %> </br>
<% end %>

app/views/bourbons/rare.html.erb
<% Bourbon.rare.each do |bourbon| %>
<%= link_to bourbon.name, bourbon_path(bourbon) %> </br>
<% end %>

app/views/bourbons/show.html.erb
<a href="#" class="js-next" data-id="<%=@bourbon.id%>">Next bourbon</a>


<h1 class="bourbonName"><%= @bourbon.name %></h1>
<h3><div class="distilleryName"> by <%= @bourbon.distillery_name %></div> </h3>
<p class="bourbonDescription"><%= @bourbon.description %></p>
<p class="bourbonAge"> AGE:<%= @bourbon.age %></p>
<p class="bourbonGrain"> GRAIN:<%= @bourbon.grain %></p>

</br>
</br>
<h3>List of Stockists:</h3>
<% @bourbon.stockists.uniq.each do |stockist| %>

<%= link_to stockist.name, stockist_path(stockist) %></br>
<% end %>

</br>
</br>
Stockist Notes :
</br>

  <% @bourbon.bourbon_stockists.each do |bourbon_stockist| %>
  <% unless bourbon_stockist.notes.nil? %>
    <%= bourbon_stockist.stockist_name %> -
    <%= bourbon_stockist.notes %>
    <%= link_to 'Edit Note', edit_bourbon_stockist_path(bourbon_stockist) %> </br>
    <%end %>
  <%end %>
</br>
</br>
</br>
<%= link_to 'Edit Bourbon', edit_bourbon_path %> </br>
<%= link_to 'All Bourbons', bourbons_path %> </br>



<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.get("/bourbons/" + nextId + ".json", function(data) {

      $(".bourbonName").text(data["name"]);
      $(".bourbonDescription").text(data["description"]);
      $(".bourbonAge").text(data["age"]);
      $(".bourbonGrain").text(data["grain"]);
      // re-set the id to current on the link
      $(".js-next").attr("data-id", data["id"]);
    });
    return false;
  });
});
</script>