config/routes.rb
Rails.application.routes.draw do
 
root 'home#index'
#get '/' => 'home#index'



  resources :distilleries do
    # nested resource for bourbon
        resources :bourbons, only: [:show, :index, :new, :edit]
         end
 resources :bourbons

 resources :stockists
 
 resources :bourbon_stockists

 get '/rare' => 'bourbons#rare'
 get '/oldest' =>'bourbons#oldest'

#get '/bourbon_stockists/new' => 'bourbon_stockists#new'
#post '/bourbon_stockists' => 'bourbon_stockists#create'
#get '/bourbon_stockists' => 'bourbon_stockists#index'


  get 'bourbons/:id/bourbon_data', to: 'bourbons#bourbon_data'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
post '/logout' => 'sessions#destroy'  #do you need this route?

get '/auth/facebook/callback' => 'sessions#create'

get '/welcome' => 'welcome#home'

#get '/signup'  => 'users#new'
#post '/signup' => 'users#create'



resources :users, only: [:new, :create]
end

app/models/distillery.rb
class Distillery < ApplicationRecord
    has_many :bourbons
    validates :name, :presence => true
end

app/controllers/distilleries_controller.rb
class DistilleriesController < ApplicationController
  before_action :require_logged_in
  before_action :find_distillery, except: [:index, :new, :create]
  helper :all

def index
  @distilleries = Distillery.all
end

def show
end

def new
  @distillery = Distillery.new
end

def create
  @distillery = Distillery.new(distillery_params)
  if @distillery.save
    redirect_to @distillery
  else
   render :new
 end
end

def edit

end

def update
  @distillery.update(distillery_params)
  if @distillery.save
    redirect_to @distillery
  else
    render :edit
   end
end

def destroy
  @distillery.destroy
  flash[:notice] = "Distillery deleted"
  redirect_to distilleries_path
end

private

def distillery_params
  params.require(:distillery).permit(:name, :address)
end

def find_distillery
  @distillery = Distillery.find(params[:id])
end

end

app/helpers/distilleries_helper.rb
module DistilleriesHelper


  def display_distillery(bourbon)
  bourbon.distillery.nil? ? link_to("Add Distillery", edit_bourbon_path(bourbon)) : link_to(bourbon.distillery_name, distillery_path(bourbon.distillery))
  end

  def distillery_select(distillery, bourbon)
    if distillery
      distillery.name
    else
      select_tag "bourbon[distillery_id]", options_from_collection_for_select(Distillery.all, :id, :name)
    end
  end

end

app/views/distilleries/_form.html.erb
<% if @distillery.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@distillery.errors.count, "error") %>
      prohibited this distillery from being saved:
    </h2>

    <ul>
    <% @distillery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @distillery  do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>

<br />

<%= f.submit %>
<% end %>

app/views/distilleries/edit.html.erb
<h1>Editing <%= @distillery.name %></h1>
<%= render partial: "form" %>
</br>
<%= link_to 'Add new Bourbon', new_distillery_bourbon_path(@distillery) %> </br>
</br>
<%= link_to "Delete Distillery", @distillery, method: :delete, data: { confirm: "Really?" } %>

app/views/distilleries/index.html.erb
<h1>Distilleries</h1>
<ul>
<% @distilleries.each do |distillery| %>
<li><%= link_to distillery.name, distillery_path(distillery) %></li>
<% end %>
</ul>
</br>
<%= link_to 'Add New Distillery', new_distillery_path%>
</br>
</br>
<%= link_to "Bourbon Index List", bourbons_path %> </br>
<%= link_to "Stockist Index List", stockists_path %>

app/views/distilleries/new.html.erb
<h1>Create a New Distillery</h1>
<%= render partial: "form" %>
</br>
</br>
<%= link_to 'Go to Distillery Index', distilleries_path%>

app/views/distilleries/show.html.erb
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

   <script src="javascripts/distilleries.js" type="text/javascript>"></script>

  </head>
  <body>

<h1><%= @distillery.name %></h1>
<h2><%= @distillery.address %> </h2></br>
<h3> List of Bourbons produced by this distillery: </h3> </br>


 <%#<ul>
<% @distillery.bourbons.each do |bourbon| %>
 <%#<li><%= link_to bourbon.name, distillery_bourbon_path(@distillery, bourbon) %><%#</li>
 <%#<% end %>
 <%#</ul>%>

 <p>
   <%= link_to 'Load Bourbons', distillery_bourbons_path(@distillery), :class => "load_bourbons" %>
   <p>

<div class="bourbons">
  <ol>
  </ol>
</div>

</br>
<%= link_to 'Add new Bourbon', new_distillery_bourbon_path(@distillery) %> </br>
</br>
<%= link_to 'Edit Distillery', edit_distillery_path %> </br>
</br>
<%= link_to 'All Distilleries', distilleries_path %>




  </body>
</html>